-- QIVORA V4 Supabase setup
-- Replace OWNER_EMAIL below with the exact owner email before running.

create table if not exists public.products (
 id bigint generated by default as identity primary key,
 name text not null,
 price text,
 category text not null default 'Other',
 image_url text not null,
 meesho_link text not null,
 created_at timestamptz not null default now()
);
alter table public.products enable row level security;
revoke all on table public.products from anon, authenticated;
grant select on table public.products to anon, authenticated;
grant insert, update, delete on table public.products to authenticated;

create policy "Public can read products" on public.products for select to anon, authenticated using (true);
create policy "Owner can insert products" on public.products for insert to authenticated
with check ((select auth.jwt() ->> 'email') = 'OWNER_EMAIL');
create policy "Owner can update products" on public.products for update to authenticated
using ((select auth.jwt() ->> 'email') = 'OWNER_EMAIL')
with check ((select auth.jwt() ->> 'email') = 'OWNER_EMAIL');
create policy "Owner can delete products" on public.products for delete to authenticated
using ((select auth.jwt() ->> 'email') = 'OWNER_EMAIL');

insert into storage.buckets (id,name,public)
values ('product-images','product-images',true)
on conflict (id) do update set public=true;

create policy "Public can view product images" on storage.objects for select to public
using (bucket_id='product-images');
create policy "Owner can upload product images" on storage.objects for insert to authenticated
with check (bucket_id='product-images' and (select auth.jwt() ->> 'email')='OWNER_EMAIL');
create policy "Owner can update product images" on storage.objects for update to authenticated
using (bucket_id='product-images' and (select auth.jwt() ->> 'email')='OWNER_EMAIL')
with check (bucket_id='product-images' and (select auth.jwt() ->> 'email')='OWNER_EMAIL');
create policy "Owner can delete product images" on storage.objects for delete to authenticated
using (bucket_id='product-images' and (select auth.jwt() ->> 'email')='OWNER_EMAIL');
